[tool.poetry]
name = "jupyter"
version = "0.1.0"
description = ""
authors = ["Marco Germanier <marco@mrgt.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
